import { chmodSync, cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// `kakapo install-app` — put a Kakapo icon in /Applications for the npm install.
//
// The npm package installs a CLI and nothing else, so kakapo exists only in a terminal: no Spotlight, no
// Launchpad, no icon to click. The .dmg on the releases page does ship a real bundle, but someone who
// installed with npm should not have to go and fetch a second copy of the same app just to get an icon.
//
// This is a COMMAND, not a postinstall step. An npm package that writes into /Applications behind your back
// is bad manners, usually needs a password, and leaves something behind that `npm uninstall` will not take
// with it. Asking for it is one line; `kakapo uninstall-app` removes it again.
//
// What it writes is a launcher: a tiny bundle whose executable execs this same CLI. It is not a copy of the
// app — that is the point. There is exactly one kakapo on the machine, the one npm manages, so an update
// through npm updates what this icon opens, with no second copy to go stale. The cost is that the Dock icon
// belongs to the Electron process the launcher starts rather than to the launcher itself.

const scriptPath = fileURLToPath(import.meta.url);
const packageRoot = dirname(dirname(scriptPath)); // dist/ -> package root

export function applicationsBundlePath(home: string = homedir()): string {
  // ~/Applications when it exists: no password, and it shows in Spotlight and Launchpad exactly like
  // /Applications does. Fall back to the system folder otherwise, which may not be writable — the caller
  // reports that as the actionable error it is rather than failing with a bare EACCES.
  const personal = join(home, "Applications");
  return existsSync(personal) ? join(personal, "Kakapo.app") : "/Applications/Kakapo.app";
}

function infoPlist(version: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Kakapo</string>
  <key>CFBundleDisplayName</key><string>Kakapo</string>
  <key>CFBundleIdentifier</key><string>dev.happynut.kakapo.launcher</string>
  <key>CFBundleVersion</key><string>${version}</string>
  <key>CFBundleShortVersionString</key><string>${version}</string>
  <key>CFBundleExecutable</key><string>kakapo-launcher</string>
  <key>CFBundleIconFile</key><string>icon.icns</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <!-- The launcher hands off to Electron and exits; without this its own icon bounces in the Dock first. -->
  <key>LSUIElement</key><true/>
</dict>
</plist>
`;
}

// The executable. `open -a` and Launchpad start it with no arguments and no useful cwd, so it opens the
// welcome screen — the same thing a double-clicked .dmg install does.
//
// It runs the CLI through the SAME node that installed it (process.execPath, baked in at install time):
// a GUI launch inherits none of your shell's PATH, so plain `node` or `kakapo` is routinely not found.
function launcherScript(nodePath: string, cliPath: string): string {
  return `#!/bin/sh
# Generated by \`kakapo install-app\`. Re-run that command after moving or reinstalling kakapo.
exec ${JSON.stringify(nodePath)} ${JSON.stringify(cliPath)} "$@"
`;
}

export type InstallAppResult = { path: string; replaced: boolean };

export function installApp(options: {
  bundlePath?: string;
  nodePath?: string;
  cliPath?: string;
  iconPath?: string;
  version?: string;
} = {}): InstallAppResult {
  if (process.platform !== "darwin") {
    throw new Error("install-app builds a macOS .app bundle; on Linux and Windows use the package from the releases page.");
  }
  const bundlePath = resolve(options.bundlePath ?? applicationsBundlePath());
  const nodePath = options.nodePath ?? process.execPath;
  const cliPath = options.cliPath ?? join(packageRoot, "bin", "kakapo.js");
  const iconPath = options.iconPath ?? join(packageRoot, "assets", "icon.icns");
  const version = options.version ?? "0.0.0";

  if (!existsSync(cliPath)) {
    throw new Error(`Cannot find the kakapo CLI at ${cliPath} — reinstall the package and try again.`);
  }

  const replaced = existsSync(bundlePath);
  try {
    rmSync(bundlePath, { recursive: true, force: true });
    mkdirSync(join(bundlePath, "Contents", "MacOS"), { recursive: true });
    mkdirSync(join(bundlePath, "Contents", "Resources"), { recursive: true });
    writeFileSync(join(bundlePath, "Contents", "Info.plist"), infoPlist(version));
    const executable = join(bundlePath, "Contents", "MacOS", "kakapo-launcher");
    writeFileSync(executable, launcherScript(nodePath, cliPath));
    chmodSync(executable, 0o755);
    if (existsSync(iconPath)) cpSync(iconPath, join(bundlePath, "Contents", "Resources", "icon.icns"));
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code === "EACCES" || code === "EPERM") {
      throw new Error(`No permission to write ${bundlePath}. Create ~/Applications (mkdir ~/Applications) and run this again, or copy the app there yourself.`);
    }
    throw error;
  }
  return { path: bundlePath, replaced };
}

export function uninstallApp(bundlePath: string = applicationsBundlePath()): boolean {
  const target = resolve(bundlePath);
  if (!existsSync(target)) return false;
  rmSync(target, { recursive: true, force: true });
  return true;
}
